# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20170514_1822'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Step',
            new_name='Video',
        ),
    ]
